// src/lib/components/subscription/BillingHistory.svelte
<script>
  import { onMount } from 'svelte';
  import { getBillingHistory } from '$lib/api/subscription-api';
  
  export let organizationId;
  
  let invoices = [];
  let loading = true;
  let error = null;
  
  onMount(async () => {
    await loadBillingHistory();
  });
  
  async function loadBillingHistory() {
    try {
      loading = true;
      error = null;
      invoices = await getBillingHistory(organizationId);
      loading = false;
    } catch (err) {
      error = err.message;
      loading = false;
    }
  }
  
  function formatDate(dateString) {
    if (!dateString) return '';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }
  
  function formatCurrency(amount) {
    if (amount === undefined || amount === null) return 'N/A';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount / 100); // Stripe amounts are in cents
  }
</script>

<div class="billing-history">
  <h3>Billing History</h3>
  
  {#if loading}
    <div class="loading">Loading billing history...</div>
  {:else if error}
    <div class="error">{error}</div>
  {:else if invoices.length === 0}
    <div class="empty">No billing history available.</div>
  {:else}
    <div class="invoices-table-container">
      <table class="invoices-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {#each invoices as invoice}
            <tr>
              <td>{formatDate(invoice.created)}</td>
              <td>
                {invoice.description || `Invoice ${invoice.number}`}
              </td>
              <td>{formatCurrency(invoice.amount_paid)}</td>
              <td>
                <span class="status-badge {invoice.status}">
                  {invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)}
                </span>
              </td>
              <td>
                {#if invoice.invoice_pdf}
                  <a href={invoice.invoice_pdf} target="_blank" rel="noopener noreferrer" class="invoice-link">
                    View Invoice
                  </a>
                {:else}
                  <span class="no-pdf">No PDF</span>
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>

<style>
  .billing-history {
    margin-top: 2rem;
  }
  
  h3 {
    margin-bottom: 1rem;
    font-size: 1.3rem;
    color: #333;
  }
  
  .loading, .error, .empty {
    text-align: center;
    padding: 1.5rem;
    background: #f9f9f9;
    border-radius: 8px;
    margin: 1rem 0;
  }
  
  .error {
    color: #d32f2f;
    background: #ffebee;
  }
  
  .invoices-table-container {
    overflow-x: auto;
    margin-top: 1rem;
  }
  
  .invoices-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.9rem;
  }
  
  .invoices-table th, .invoices-table td {
    padding: 0.75rem;
    text-align: left;
    border-bottom: 1px solid #eee;
  }
  
  .invoices-table th {
    background-color: #f5f5f5;
    font-weight: bold;
  }
  
  .invoices-table tr:hover {
    background-color: #f9f9f9;
  }
  
  .status-badge {
    display: inline-block;
    padding: 0.25rem 0.5rem;
    border-radius: 20px;
    font-size: 0.8rem;
    font-weight: bold;
  }
  
  .status-badge.paid {
    background-color: #e8f5e9;
    color: #2e7d32;
  }
  
  .status-badge.open {
    background-color: #e3f2fd;
    color: #1565c0;
  }
  
  .status-badge.uncollectible {
    background-color: #ffebee;
    color: #c62828;
  }
  
  .status-badge.void {
    background-color: #f5f5f5;
    color: #616161;
  }
  
  .invoice-link {
    color: #2196f3;
    text-decoration: none;
    font-weight: bold;
  }
  
  .invoice-link:hover {
    text-decoration: underline;
  }
  
  .no-pdf {
    color: #9e9e9e;
    font-style: italic;
  }
</style>

// src/app/settings/subscription/billing-history/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { SubscriptionInvoice } from '@/lib/services/subscription-service';

export default function BillingHistoryPage() {
  const [organizationId, setOrganizationId] = useState<string>('');
  const [invoices, setInvoices] = useState<SubscriptionInvoice[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  const router = useRouter();

  useEffect(() => {
    // Get organization ID and user ID from session
    const getOrgId = async () => {
      try {
        const response = await fetch('/api/auth/session');
        const session = await response.json();
        
        if (session?.user) {
          const orgId = (session.user as any)?.organizationId;
          const userId = session.user.id;
          
          if (orgId) {
            setOrganizationId(orgId);
          } else if (userId) {
            // For individual users, use userId as identifier
            setOrganizationId(userId);
          } else {
            setError('No organization or user found. Please log in again.');
          }
        } else {
          setError('Please log in to view billing history.');
        }
      } catch (err) {
        console.error('Error fetching session:', err);
        setError('Failed to load session. Please try again later.');
      }
    };

    getOrgId();
  }, []);

  useEffect(() => {
    if (!organizationId) return;

    const fetchInvoices = async () => {
      setIsLoading(true);
      setError(null);
      
      try {
        // Try both organizationId and userId parameters for compatibility
        const response = await fetch(`/api/subscription/invoices?organizationId=${organizationId}&userId=${organizationId}&limit=50`);
        if (!response.ok) throw new Error('Failed to load invoices');
        
        const data = await response.json();
        setInvoices(data.invoices || []);
      } catch (err) {
        console.error('Error fetching invoices:', err);
        setError('Failed to load billing history. Please try again later.');
      } finally {
        setIsLoading(false);
      }
    };

    fetchInvoices();
  }, [organizationId]);

  const formatDate = (dateString?: string) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString();
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount);
  };

  const getStatusBadgeClass = (status: string) => {
    switch (status) {
      case 'paid':
        return 'bg-green-100 text-green-800';
      case 'unpaid':
        return 'bg-yellow-100 text-yellow-800';
      case 'void':
        return 'bg-gray-100 text-gray-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  if (isLoading) {
    return (
      <div className="p-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold mb-6">Billing History</h1>
          <div className="animate-pulse space-y-4">
            <div className="h-10 bg-gray-200 rounded w-full"></div>
            <div className="h-40 bg-gray-200 rounded w-full"></div>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold mb-6">Billing History</h1>
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded relative" role="alert">
            <strong className="font-bold">Error: </strong>
            <span className="block sm:inline">{error}</span>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold">Billing History</h1>
          <button 
            onClick={() => router.push('/settings/subscription')}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
          >
            Back to Subscription
          </button>
        </div>
        
        {invoices.length > 0 ? (
          <div className="bg-white shadow overflow-hidden rounded-lg">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Invoice Date
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Due Date
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Amount
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {invoices.map((invoice) => (
                  <tr key={invoice.id}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {formatDate(invoice.created_at)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {formatDate(invoice.due_date)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {formatCurrency(invoice.amount)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${getStatusBadgeClass(invoice.status)}`}>
                        {invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {invoice.invoice_pdf && (
                        <a 
                          href={invoice.invoice_pdf} 
                          target="_blank" 
                          rel="noopener noreferrer"
                          className="text-blue-600 hover:text-blue-800"
                        >
                          Download PDF
                        </a>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="bg-white shadow rounded-lg p-6 text-center">
            <p className="text-gray-500">No billing history available.</p>
          </div>
        )}
      </div>
    </div>
  );
}
